channels:
  - name: sig-release
  - name: release-bug-triage  
  - name: release-ci-signal
  - name: release-comms
  - name: release-docs
  - name: release-enhancements
  - name: release-management
    id: CJH2GBF7Y
  - name: release-notes
  - name: release-packages-poc
